[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlcog"
version = "0.1.0"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]
include = ["mlcog*"]
